config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  resources :articles
  resources :users
  resources :categories, except: [:destroy]
  resources :messages
  resources :courses
  resources :students
  get "teacher_info", to: "students#teacher_info"
  post 'course_enroll', to: 'student_courses#create'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
    @users = User.all
    @message = Message.new
  end

  def new
    @message = Message.new
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      flash[:notice] = "Message was created successfully!"
      redirect_to messages_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    if @message.update(message_params)
      flash[:notice] = "Message was updated successfully!"
      redirect_to messages_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    flash[:notice] = "Message was deleted successfully!"
    redirect_to message_path
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/views/messages/_form.html.erb
<%= render 'layouts/errors', object: @message %>
<%= form_with model: @message do |form| %>
  <div class="row">
    <div class="col-md-10 binput-group">
      <%= form.text_field :body,class:"form-control" %>
    </div>
    <%=form.hidden_field :user_id, value: current_user.id,  class: 'form-control'%>
    <div class="col-md-2 mt-1">
      <%= form.submit "send",class:'text-danger'%>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<span class="btn btn-outline-danger rounded-pill bg-danger-gradient text-dark my-2"><em><%=message.user.username %></em> : <%=link_to message.body, message_path(message), class:'text-decoration-none text-dark'%></span><br/>

app/views/messages/_subheader.html.erb
  <div class="d-flex justify-content-center">
    <i class="fa-solid fa-mug-saucer fa-5x text-danger"></i>
  </div>
  <div class="d-flex justify-content-center">
    <p class="fs-5 text-danger py-3">Say something</p>
  </div>

app/views/messages/edit.html.erb
<div class="container mt-5">
  <h1 class="text-center m-2">Edit Message</h1>
    <%= render 'form', message: @message %>
<div>

app/views/messages/index.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-center">
    <i class="fa-solid fa-mug-saucer fa-5x text-danger"></i>
  </div>
  <div class="d-flex justify-content-center">
    <p class="fs-5 text-danger py-3">Say something</p>
  </div>
  <div class="row">
    <div class="col-md-9 col-sm-8 ">
      <div class="card">
        <div class="card-body ">
          <%@messages.each do|message|  %>
            <%= render partial: 'messages/message', locals: {message: message} %>
          <%end%>
          <div class="card-footer">
            <%= render partial: 'messages/form'%>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-4 w-sm-100 text-center">
      <div class="card">
       <p class="fs-4 fw-bold btn btn-danger"><i class="fa-solid fa-users"></i> User List</p>
        <div class="card-body">
          <% @users.each do |user| %>
            <div class="border py-1"><span class="btn btn-outline-danger rounded-pill bg-danger-gradient text-dark mt-1"><i class="fa fa-user"></i> <%= user.username %></span></div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<div class="container mt-5">
  <h1 class="text-center m-2">New Message</h1>
    <%= render 'form', message: @message %>
<div>

app/views/messages/show.html.erb
<div class="container mt-4">
  <div class="row d-flex justify-content-center text-center">
    <div class="col-md-9 ">
      <div class="card">
        <div class="card-body">
          <div class="card-text text-danger"><%=@message.body %></div>
          <span class="badge rounded-pill bg-info text-dark">Created <%=time_ago_in_words @message.created_at %> ago,</span>
          <span class="badge rounded-pill bg-info text-dark">updated <%=time_ago_in_words @message.updated_at %> ago</span>
          <span class="d-flex justify-content-center mt-2">
            <%= link_to edit_message_path(@message), class:"btn btn-outline-warning mx-2" do %>
              Edit
            <%end%>
            <%= button_to 'Delete',  message_path(@message),  method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-outline-danger" %>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>