config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  resources :articles
  resources :users
  resources :categories, except: [:destroy]
  resources :messages
  resources :courses
  resources :students
  get "teacher_info", to: "students#teacher_info"
  post 'course_enroll', to: 'student_courses#create'
end

app/views/shared/_article_navbar.html.erb
<% if params[:controller] == 'articles' || params[:controller] == 'categories' || params[:controller] == 'users'%>
  <%= link_to articles_path, class: "nav-link mx-2 text-color-blue #{'btn btn-outline-primary rounded-pill bg-primary-gradient' if current_page?(articles_path)}" do %>
    <div class="fa-brands fa-blogger"></div>
    Blog list
  <%end%>
  <%= link_to new_article_path, class: "nav-link text-color-blue #{'btn btn-outline-primary rounded-pill bg-primary-gradient' if current_page?(new_article_path)}" do %>
    <div class="fa-solid fa-square-plus"></div>
    New blog
  <%end%>
  <%= link_to categories_path, class: "nav-link text-color-blue #{'btn btn-outline-primary rounded-pill bg-primary-gradient' if current_page?(categories_path)}" do %>
    <div class="fa-solid fa-layer-group"></div>
    Categories list
  <%end%>
  <%= link_to users_path, class: "nav-link text-color-blue #{'btn btn-outline-primary rounded-pill bg-primary-gradient' if current_page?(users_path)}" do %>
    <div class="fa-solid fa-users"></div>
    Users list
  <%end%>
<%end%>

app/views/shared/_courses_navbar.html.erb
<% if params[:controller] == 'courses' || params[:controller] == 'students' %>
  <%= link_to courses_path, class: "nav-link text-color-blue #{'btn btn-outline-primary rounded-pill bg-primary-gradient ' if current_page?(courses_path)}" do %>
    <div class="fa-solid fa-book-open"></div>
    Course list
  <%end%>
  <%= link_to students_path, class: "nav-link text-color-blue #{'btn btn-outline-primary rounded-pill bg-primary-gradient ' if current_page?(students_path)}" do %>
    <div class="fa-solid fa-user-graduate""></div>
    Students list
  <%end%>
  <%= link_to teacher_info_path, class: "nav-link  text-color-blue #{'btn btn-outline-primary rounded-pill bg-primary-gradient' if current_page?(teacher_info_path)}" do %>
    <div class="fa-solid fa-graduation-cap"></div>
    Teacher list
  <%end%>
  <% if current_user %>
    <%= link_to student_path(current_user), class: "nav-link  text-color-blue #{'btn btn-outline-primary rounded-pill bg-primary-gradient' if current_page?(student_path(current_user))}" do %>
      <div class="fa-solid fa-user"></div>
      View your profile
    <% end %>
  <%end%>
<%end%>

app/views/shared/_messages_nav.html.erb
<% if params[:controller] == 'messages'%>
  <%= link_to messages_path, class: "nav-link #{'btn btn-outline-primary rounded-pill bg-primary-gradient text-color-blue' if current_page?(messages_path)}" do %>
    <div class="fa-solid fa-message"></div>
    Message
  <%end%>
<%end%>