config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  resources :articles
  resources :users
  resources :categories, except: [:destroy]
  resources :messages
  resources :courses
  resources :students
  get "teacher_info", to: "students#teacher_info"
  post 'course_enroll', to: 'student_courses#create'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      flash[:notice] = "Coures was updated successfully!"
      redirect_to @course
    else
      render :edit
    end
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "Coures was created successfully!"
      redirect_to @course
    else
      render :new
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    flash[:notice] = "Course was deleted successfully!"
    redirect_to courses_path
  end

  private

  def course_params
    params.require(:course).permit(:short_name, :name, :description)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div class="col-md-6 m-3">
  <%= link_to course_path(course),class:'text-decoration-none text-dark' do %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Course code : <%=course.short_name%></h5>
        <h6 class="card-subtitle mb-2 text-info">Course name : <%=course.name%></h6>
        <p class="card-text">Description : <%=course.description%></p>
        <span class="d-flex justify-content-center">
          <% if !current_user.courses.include?(course) && !current_user.admin?%>
            <%= button_to 'Enroll', course_enroll_path(course_id: course.id), method: :post, class: 'btn btn-outline-primary card-link'%>
          <% end %>
          <a href="#" class="card-link"></a>
        </span>
      </div>
      <% if current_user.admin%>
        <span class="card-footer d-flex justify-content-center">
          <%=link_to "Edit", edit_course_path( course), class:'btn btn-outline-warning mx-2'%>
          <%= button_to 'Delete',  course_path(course),  method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-outline-danger" %>
        </span>
      <%end%>
    </div>
  <%end%>
</div>

app/views/courses/_form.html.erb
<%= render 'layouts/errors', object: @course %>
<div class="container mt-5 shadow-lg p-3 mb-5 bg-info rounded">
  <%= form_with model: @course do |form| %>
    <div>
      <%= form.label :short_name %><br>
      <%= form.text_field :short_name,class: 'form-control shadow-lg' %>
    </div>
    <br />
    <div>
      <%= form.label :name %><br>
      <%= form.text_area :name, class: 'form-control  shadow-lg'%>
    </div>
    <br/>
    <div>
      <%= form.label :Description %><br>
      <%= form.text_area :description, class: 'form-control  shadow-lg'%>
    </div>
    <br/>
    <div>
      <%#=form.hidden_field :user_id, value: current_user.id,  class: 'form-control'%>
    </div>
    <br />
    <div>
      <%= form.submit  class: 'btn btn-outline-light btn-lg text-dark'%>
    </div>
    <br />
  <% end %>
</div>
<div class="container mt-5 text-center">
  <%= link_to  "Return to course listing", courses_path,class: 'btn btn-outline-light btn-lg text-dark'%>
</div>

app/views/courses/edit.html.erb
<div class="container mt-5">
  <h1 class="text-center m-2">Edit Course</h1>
    <%= render 'form', course: @course %>
<div>

app/views/courses/index.html.erb
<div class="bg-primary-gradient">
  <h1 class="text-center py-4">Listing of all courses</h1>
</div>
<div class="container">
  <div class="row d-flex justify-content-center">
    <%@courses.each do |course| %>
      <%= render partial: 'courses/course', locals: {course: course} %>
    <%end%>
  </div>
</div>

app/views/courses/new.html.erb
<div class="container mt-5">
  <h1 class="text-center m-2">Create a new Course</h1>
    <%= render 'form', course: @course %>
<div>

app/views/courses/show.html.erb
<div class="bg-primary-gradient">
  <h1 class="text-center py-4"><%=@course.name%></h1>
</div>
<div class="container">
  <div class="row d-flex justify-content-center">
    <%= render partial: 'courses/course', locals: {course: @course} %>
  </div>
</div>