config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  resources :articles
  resources :users
  resources :categories, except: [:destroy]
  resources :messages
  resources :courses
  resources :students
  get "teacher_info", to: "students#teacher_info"
  post 'course_enroll', to: 'student_courses#create'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 40 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
  paginates_per 3
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :show]
  before_action :set_user, except: [:index, :show]

  def index
    @categories = Category.page params[:page]
    @users_all = User.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category was updated successfully!"
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully!"
      redirect_to @category
    else
      render "new"
    end
  end

  def show
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_user
    if !current_user.admin?
      flash[:alert] = "You are not able to perform this action."
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/views/categories/_category.html.erb
<div class="row d-flex justify-content-center mt-4">
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title text-success text-center"><%= category.name %></h5>
      </div>
      <div class="card-body">
        <p class="text-center"><%= pluralize(category.articles.count, "article") %></p>
        <span class="d-flex justify-content-center">
          <% unless params[:controller] == 'categories' && params[:action] == 'show' %>
            <%= link_to 'View', category_path(category), class:"btn btn-outline-success mx-2" %>
          <% end %>
          <% if  current_user.admin? %>
            <%= link_to 'Edit', edit_category_path(category), class:"btn btn-outline-info mx-2" %>
          <% end %>
        </span>
      </div>
      <div class="card-footer text-muted">
        Created <%=time_ago_in_words category.created_at %> ago,
        edited <%=time_ago_in_words category.updated_at %> ago
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= render 'layouts/errors', object: @category%>
<div class="container mt-5 shadow-lg p-3 mb-5 bg-info rounded">
  <%= form_with model: @category do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name,class: 'form-control shadow-lg ' %>
    </div>
    <br />
    <div>
      <%= form.submit  class: 'btn btn-outline-light btn-lg text-dark'%>
    </div>
    <br />
  <% end %>
</div>
<div class="container mt-5 text-center">
  <%= link_to  "Return to Article listing", articles_path,class: 'btn btn-outline-light btn-lg text-dark'%>
</div>

app/views/categories/_sidebar.html.erb
<div  class="text-center bg-primary-gradient mt-5">
  <div class="border py-5">
    <h3 class="fa-solid fa-layer-group text-color-blue"></h3>
    <h3 class="text-color-blue d-inline">List of category</h3>
  </div>
  <% @categories.each do |category| %>
    <%= link_to category,class:'text-decoration-none'  do%>
      <div class="fs-5 border py-5">
        <%= category.name%>
      </div>
    <%end%>
  <%end%>
</div>

app/views/categories/edit.html.erb
<div class="container mt-5">
  <h1 class="text-center m-2">Edit category</h1>
    <%= render 'form', category: @category %>
<div>

app/views/categories/index.html.erb
<div class="bg-primary-gradient">
  <h1 class="text-center py-4">Categories list</h1>
</div>
<% if  current_user.admin? %>
  <h5 class="text-center my-4"><%= link_to 'Add new category', new_category_path, class:'btn btn-success'%></h5>
<%end%>
<div class="row">
  <div class="col-md-2 m-0">
    <%= render 'categories/sidebar' %>
  </div>
  <div class="col-md-8">
    <div class="container d-flex justify-content-center my-5">
      <%= paginate @categories, remote: true  %>
    </div>
    <% @categories.each do |category| %>
      <%= render partial: 'categories/category', locals: { category: category} %>
    <% end %>
    <div class="container d-flex justify-content-center my-5">
      <%= paginate @categories, remote: true  %>
    </div>
  </div>
  <div class="col-md-2 m-0">
    <%= render 'users/sidebar' %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container mt-5">
  <h1 class="text-center m-2">Add a new category</h1> 
    <%= render 'form', category: @category %>
<div>

app/views/categories/show.html.erb
<div class="container mt-5">
  <h1 class="text-center m-2">Category:  
    <%= @category.name%></h1>
  <%= render partial: 'categories/category', locals: { category: @category} %>
  <% @category.articles.each do |category| %>
    <%= render partial: 'articles/article', locals: {article: category} %>
  <% end %>
</div>